
Description = "amos-7.blue"

Default       = { Colour="#0647C3" }
Canvas        = { Colour="#09052A" }
Number        = { Colour="#47C306" }
Escape        = { Colour="#C58D07" }
String        = { Colour="#47C306" }
BlockComment  = { Colour="#4427AC" }
LineNum       = BlockComment
Operator      = Default
LineComment   = BlockComment
PreProcessor  = Default
StringPreProc = String
Interpolation = Escape

Keywords = {
  { Colour="#0647C3" },
  { Colour="#0647C3" , Bold=true },
  { Colour="#47C306" },
  { Colour="#4427AC" },
}
