## [:< ##

# name  = base.list.init
# args  = { key_data_ref max_elements }

my $key_data_ref         = shift;
my $max_elements_default = 13747;

if ( ref $key_data_ref ne qw| HASH | ) {
    <[base.log]>->( 0, 'base.list.init: submitted argument is no hash' );
    return undef;
}

if ( not defined $key_data_ref->{'max_elements'}
    or $key_data_ref->{'max_elements'} < 1 ) {
    <[base.logs]>->(
        0, "base.list.init: 'max_elements' not set, defaulting to %u .,",
        $max_elements_default
    );
    $key_data_ref->{'max_elements'} = $max_elements_default;
}

if ( not defined $key_data_ref->{'key_ref'}
    or ref $key_data_ref->{'key_ref'}->$* ne qw| HASH | ) {
    <[base.log]>->(
        0,
        "base.list.init: 'key_ref' is neither a hash nor a scalar reference"
    );
    return undef;
}

<base.element>->{ $key_data_ref->{'key_ref'} } = {
    'name'      => $key_data_ref->{'name'} // qw| unnamed |,
    'max_count' => $key_data_ref->{'max_elements'},
    'count'     => scalar keys $key_data_ref->{'key_ref'}->$*->%*
};

#,,,.,.,,,.,.,...,,..,.,,,,.,,.,.,,..,,,.,..,,..,,...,..,,.,.,,,,,,,.,.,,,...,
#TTQ3YGUR7GLKXOKDMSEWWJBMHY22KF23RI6BNDLJSN74ZUROCGSVEY6E7FPAFVJFRTHC6LP3LIJ5O
#\\\|33IXYHZ6GVCGN2IUPUYBI3C3VCBKVDCS7E67CAXVCEMXYZYZ6XA \ / AMOS7 \ YOURUM ::
#\[7]7XIN6TQGE5I4ES2ZEIH6NY6DVISKX5A6XQTZ6BGAEJCFTJPMTQDA 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
