## [:< ##

# name  = base.bmw384.index.init
# descr = initialize bmw384 field index structure

<bmw384.index> //= { qw| by_name | => {}, qw| by_arc | => {} };

for my $ARG ( 0 .. 25 ) {
    <bmw384.index>->{'by_arc'}{$ARG} //= [];
}

return <bmw384.index>;

#,,,,,,.,,,,.,..,,,.,,,,.,,.,,,,,,.,.,,..,..,,..,,...,...,,..,,..,,.,,.,.,.,,,
#JDTU4UG3FTUTNWTKGZMVFBCAPAZL7UQ32ZGQ2ZZF37MIZGUU4YWZBDJK56WQPJFZOCXSJK2Q2YDHU
#\\\|VPD5AA7JSNYDTFQGWZEYMY6NC3W5YXLPXY5IKFB77IX4MPORX77 \ / AMOS7 \ YOURUM ::
#\[7]IPLL5BNAMNA4YHVSICKAL45M7BCB7N5VUCD7UPLQGEJA5WIIGQBQ 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
