## [:< ##

# name = base.perlmod.install

my $module_name = shift;
my $cpanm_path  = <system.bin_path.cpanm>;
my $known_deps  = <[base.known_dependencies]>->{'perlmod'}->{$module_name}
    // {};

$module_name = $known_deps->{'cpan'}
    if defined $known_deps->{'cpan'}
    and $known_deps->{'cpan'} ne $module_name;

<[base.logs]>->( 1, ".: installing perl module '%s' :.", $module_name );

<system.host.os.dist.name> //= qw| unknown |;
<system.host.os.dist.name> = qw| debian |
    if <system.host.os.dist.name> eq qw| unknown |
    and -f qw| /etc/os-release |
    and <[file.content]>->('/etc/os-release') =~ m|^ID(_LIKE)?=debian$|m;

my @cpan_list = ($module_name);

if (    <system.host.os.dist.name> eq qw | debian |
    and defined $known_deps->{'debian'}
    and ref( $known_deps->{'debian'} ) eq qw| ARRAY |
    and $known_deps->{'debian'}->@* ) {
    @cpan_list = ();
    my @deb_list;
    map {
        if ( $ARG =~ s|^cpan:|| ) {
            push @cpan_list, $ARG;
        } else {
            push @deb_list, $ARG;
        }
    } $known_deps->{'debian'}->@*;

    <[base.debian.install_package]>->(@deb_list);
}

if (@cpan_list) {
    if ( not length $cpanm_path ) {    ## create seperate routine ##  [LLL]
        <[base.log]>->( 0, "[AUTO_INSTALL] 'cpanminus' ..." );
        if ( <system.host.os.dist.name> eq qw| debian | ) {
            system qw| apt-get -fy install cpanminus |;
        } else {                       # LLL: CHECKSUM and config !!!
            qx'wget https://cpanmin.us -O /var/tmp/autoinst.cpanm';
            system qw| /var/tmp/autoinst.cpanm --self-upgrade |;

        }
    }

    my $s = @cpan_list > 1 ? 's' : '';
    <[base.logs]>->(
        0,  '[AUTO_INSTALL] module%s: %s',
        $s, join( ', ', @cpan_list )
    );
    system( $cpanm_path, @cpan_list );
}

#,,.,,,,.,...,,,.,.,,,...,,,,,.,.,,,.,,.,,.,.,..,,...,...,,..,.,.,.,.,,,.,,..,
#DMISR7SSUXX57J5ATD2Q3X3OY4BELLX5UMC6SPR6EYS6TLMPXSEHGHD6GA2O733I7VTTSFYUEV37E
#\\\|DB2I5UWLD4QI7U3MBG775N4FJ6JCKAYILZIWGRR2OSXUPBSZJCC \ / AMOS7 \ YOURUM ::
#\[7]VN3UGSCX6TW22YEJ5RYLIXQTDCYFKO5AKHLV36YJMRE2HHJSPIDA 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
