## [:< ##

# name  = filter.init

#,,,,,,.,,,..,..,,.,,,,..,,..,,.,,...,,.,,,.,,..,,...,...,,,.,...,,,,,..,,.,,,
#LKAUELX4TZVHTLFVQ6KPROZSUB222OODCGSHLGPZBSCNGRVOPVRS2N5FG5AQ4XN5YFDI5455VUIBK
#\\\|3TNSHCIBLRAXIYZRQO6JTALGCYOZO2RIMY2WTRNQVQXVA6MFYKP \ / AMOS7 \ YOURUM ::
#\[7]KHV7VPKTM266663QEQVDLFEK43BLJHXRTMDXJTSLVFX2ICIEN6BY 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
