## >:] ##

# name  = filter.init

#,,.,,,..,...,,.,,,,,,,,.,,..,,..,.,.,..,,,,.,..,,...,...,.,,,.,,,.,,,,..,,,,,
#2OSJDKXKDQIGC72JJ5U4WDDWA3UP7Y2XEIYKXUSEHZGP6BWVMXTDIJMEDKUP53NBBOBOZ3ICXHIQY
#\\\|ULG7VDTLXEKZHF4SPSLGTHNQQ2U3ED7ROXU2E4WWJO6GI5AHMRK \ / AMOS7 \ YOURUM ::
#\[7]LZQEAWADB643CIC3XCXAOAYAXH7GHN6D2QRFSBJXQLMIBSU6R4BQ 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
