## [:< ##

# name  = filter.init

#,,..,.,.,,.,,,..,...,,,,,,..,...,,.,,.,.,.,.,..,,...,..,,.,,,,,.,...,,,,,,.,,
#UK7PBWFC67RTWIBFH6R4JVURVRBELTCSKSZAAL5O7DDGCIOY2SWFNCG27URE73FMXWAQHCH5QKY4A
#\\\|LXEF4DQKKYSPAMPWCGSA23J6LDLBP7O3NFK6YAQ33QXXOKVV56I \ / AMOS7 \ YOURUM ::
#\[7]O4HBNQBFTIBQSC6ZT3PX3SVYHC5VQW7SMVWZMZCEAQ53YIU3IAAY 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
