## [:< ##

# name  = graphics-matrix.cursor.init
# descr = initialize cursor state in graphics-matrix namespace

## initialize cursor state in data tree ##
$data{'graphics-matrix'}{'cursor'} = {
    qw| selX   | => <graphics-matrix.cursor.initial_x> // 0,
    qw| selY   | => <graphics-matrix.cursor.initial_y> // 0,
    qw| selZ   | => <graphics-matrix.cursor.initial_z> // 0,
    qw| zoom   | => 1.0,
    qw| radius | => 1,
};

my $cursor = $data{'graphics-matrix'}{'cursor'};

<[base.logs]>->(
    2, 'cursor initialized at [%d,%d,%d]',
    $cursor->{'selX'}, $cursor->{'selY'}, $cursor->{'selZ'}
);

#,,,.,...,.,,,.,.,,,,,,,.,,,,,.,.,,,,,,.,,,.,,.,.,...,...,.,.,,..,,,.,...,...,
#XJTW2EN5ICLZK4MTD7DLZ4YFBZHV4KDXRZSS63VFQWZJFJ77INOFAL2FB6WPZDFYVVOSHHWWKMOTI
#\\\|ABKUY56OPLKW3LEPRS42JI6XMRLBHAAEG2AOU52MRR6E6X7UUIF \ / AMOS7 \ YOURUM ::
#\[7]CEQ72IXYR5LCPRMF6XZNUWBOUOJYTHLKB6JBRBHYIYQAAWWTQ4AQ 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
