## [:< ##

# name  = graphics-matrix.graph.init
# descr = initialize similarity graph state

$data{'graphics-matrix'}{'graph'} = {
    qw| edges    | => {},
    qw| clusters | => {},
    qw| count    | => 0,
};

<[base.logs]>->( 2, 'graph initialized' );

#,,,.,.,.,...,,,,,,.,,...,.,,,,,,,,,.,,,.,..,,..,,...,...,...,,,,,...,,..,.,,,
#5BTSSW23LE3VYMB2FJA4CQZGXCJCTS3EXZQ6G3XSEQVXFNMQVIPI4RQGNRG5XEEC2C642WMBDNXOW
#\\\|Q4O42GGIM7QJF42MAKF3GON244BLKL4VVJIAG5BL6HU6DMENA77 \ / AMOS7 \ YOURUM ::
#\[7]L2S7ZU2MNMQJ6J7IQSTRNFSL3JF4IJRKMMK2SDUJTI5YXR3LJEAY 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
