## [:< ##

# name  = graphics-matrix.cell.init
# descr = initialize lattice cell storage

## set up cell storage ##
$data{'graphics-matrix'}{'cell'} = {
    qw| cells | => {},
    qw| count | => 0,
};

<[base.logs]>->( 2, 'cell storage initialized' );

#,,,.,.,,,,..,,..,,,,,...,.,,,...,.,.,,..,.,,,..,,...,.,.,,..,..,,,,,,,.,,,.,,
#SQWI37KSCQZ6GJKQR6F72DNHD7TUOW2EJS7OL3SZZTKDIVV7GENGGXKRLCQC5D2SUE6KWSP2FLPAY
#\\\|ZHX3HEMSJB2FPZLBVR6GROJGXV4PTPNG7DCII6T5VWU5COKQELX \ / AMOS7 \ YOURUM ::
#\[7]R3AMOM6ZQVKJM7VBBLVFDMWWOJT5T7PEKA4PI6KJGS6WAKJU3CBQ 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
