## [:< ##

# name  = graphics-matrix.address.init
# descr = initialize address registry

## set up address registry ##
$data{'graphics-matrix'}{'address'} = {
    qw| checksum | => {},
    qw| label    | => {},
};

## register current cursor position as origin ##
my $cursor = $data{'graphics-matrix'}{'cursor'};
<[graphics-matrix.address.register]>->(
    {   qw| position | => {
            qw| selX | => $cursor->{'selX'},
            qw| selY | => $cursor->{'selY'},
            qw| selZ | => $cursor->{'selZ'},
        },
        qw| label | => qw| origin |,
    }
);

<[base.logs]>->( 2, 'address registry initialized' );

#,,..,,.,,,,,,,,,,,..,.,,,..,,,.,,,,.,,,.,...,..,,...,...,...,,,,,...,,,,,,..,
#2O5Q6Q4VEFC2PY3GDG4B53KXP4PKGOUA3KSFKQQPS5B2HQAPBPD7RRWYSFEBTYCBQBXBKGJIPX5XC
#\\\|3WVE7G6WB2UYDHHHUWDMDZP2UAEQ6BTS5BRNFOPX64YYFMCMHBA \ / AMOS7 \ YOURUM ::
#\[7]SNZQFFAPKH5AD3XL4UH6FR6POPNHAMIH2JWDGCFOR7L2J5H7PKBY 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
