## [:< ##

# name  = job-site-scan.assert.init
# descr = create assertion tree template for a job entry

my $job_id = shift // return;

my $assertions = {
    'suggest' => {
        'apply'   => 'undecided',
        'delete'  => 'undecided',
        'archive' => 'undecided',
    },
    'dimensions' => {
        'location' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'work-profile' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'company-culture' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'compensation' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'remote-flexibility' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'career-growth' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'tech-stack' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'team-structure' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
    }
};

<job-site-scan.tasks>->{$job_id}{'assertions'} = $assertions;

return $assertions;

#,,..,,.,,,,.,.,,,..,,..,,,..,.,.,...,,.,,.,,,..,,...,...,..,,.,.,..,,,.,,.,,,

#,,.,,,.,,,..,,,,,...,,..,,..,.,.,...,..,,..,,..,,...,...,..,,,.,,...,,,,,.,.,
#S2EOBC2OODMLKUOOA4HTQMB4RSVFSHIQPY2NDF4ISORGHP3KEXP2K5SKBCYSKIGH37CNPEDAHARHW
#\\\|QKMCCYSKIOBKTXRNMDFVAFSYF4N6DA2TLYYASCP34BH4CDJNCQN \ / AMOS7 \ YOURUM ::
#\[7]YB6RJLWD7XMIJKRYYGUIDQHJ2G6TFRD6XU2IIMFJSFBR47WN5OAI 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
