## [:< ##

# name  = jobsite.assert.init
# descr = create assertion tree template for a job entry

my $job_id = shift // return;

my $assertions = {
    'suggest' => {
        'apply'   => 'undecided',
        'delete'  => 'undecided',
        'archive' => 'undecided',
    },
    'dimensions' => {
        'location' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'work-profile' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'company-culture' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'compensation' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'remote-flexibility' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'career-growth' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'tech-stack' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'team-structure' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
    }
};

<jobsite.tasks>->{$job_id}{'assertions'} = $assertions;

return $assertions;

#,,..,,,.,...,,..,,..,,,,,.,,,...,...,..,,,,,,..,,...,...,.,,,.,.,,.,,,,.,..,,
#7PZ7KC6KIREUZI4CC5AHBWYH3TXOEUJURMSLEYYE4JZCON4XLC6TRGTJ5PG2FBEDCOKZGHJPO75AU
#\\\|2EVDQ2WPCG42MDPKXEZSBSOBZMETO2YK4ZQMWOWFEYSIARZ22UC \ / AMOS7 \ YOURUM ::
#\[7]VHMVKD53QNX3TNLH75YSYA4WSUO6TMU2KLOPELOFZ6MHGFE6BYDY 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
