## [:< ##

# name  = radio.audio.init
# descr = start mpv[audio-0] background player via v7 on-demand

##  clear any pending re-init timer  ##
delete <radio.audio.reinit_watcher>;

<[protocol-7.route-send]>->(
    {   'command'   => 'v7.notify_online',
        'call_args' => { 'args' => 'mpv[audio-0]' },
        'reply'     => {
            'handler' => 'radio.audio.handler.player_online',
            'params'  => { 'instance' => 'mpv[audio-0]' },
        }
    }
);

<[protocol-7.route-send]>->(
    {   'command'   => 'v7.notify_offline',
        'call_args' => { 'args' => 'mpv[audio-0]' },
        'reply'     => {
            'handler' => 'radio.audio.handler.player_offline',
            'params'  => { 'instance' => 'mpv[audio-0]' },
        }
    }
);

<[protocol-7.route-send]>->(
    {   'command'   => 'v7.start_once',
        'call_args' => { 'args' => 'mpv[audio-0]' },
    }
);

<[base.logs]>->( 2, '[radio.audio] waiting for mpv[audio-0] ...' );

#,,,.,.,,,,,,,...,..,,.,.,,.,,.,.,,..,...,,,,,.,.,...,...,..,,...,...,.,,,..,,
#NN6EJKFQFQC7YFB7ZKTP7UCDHTF3O57PJKP37S4QDOJWYACYOUT4SQB7IMNXPSTJMGVJX2PNNRNGW
#\\\|QSN5MB4QGV6VSPJ6QLPOYPTWIVJ4JLNG47YXUM5PBOX5Z46PL2K \ / AMOS7 \ YOURUM ::
#\[7]6JV7SSOZB5ALZ4GHG2JJKRYMQTHBBH2QPJ4YGY2KPHSLKKC72GAY 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
