## [:< ##

# name  = route.bmw384.index.init
# descr = initialize bmw384 field index structure

<bmw384.index> //= { qw| by_name | => {}, qw| by_arc | => {} };

<bmw384.index>->{'degree_density'}     = [ (0) x 360 ];
<bmw384.index>->{'degree_density_max'} = 0;

for my $ARG ( 0 .. 25 ) {
    <bmw384.index>->{'by_arc'}{$ARG} //= [];
}

return <bmw384.index>;

#,,.,,...,.,.,...,,,,,.,.,,.,,,,,,,,.,,,.,,.,,..,,...,...,..,,..,,...,,..,,,,,
#OH73N5WYY6HWHGKRX56ICFJ7B6MU2QAANLRG4B57AJV42I7VI6ZTIF3AA3B3JSYXSVDILEWLRNFJ6
#\\\|FEHO6DZXNFOFJVPDKXADSU74TKQVDWQZSNSIB2T6QHW233BB23O \ / AMOS7 \ YOURUM ::
#\[7]7Q76PZQPMKPZMSQCXCJENAEQP4XOTMHESGRJW62MK7KUVQKAF6AA 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
