## [:< ##

# name  = route.bmw384.index.init
# descr = initialize bmw384 field index structure

<bmw384.index> //= { qw| by_name | => {}, qw| by_arc | => {} };

for my $ARG ( 0 .. 25 ) {
    <bmw384.index>->{'by_arc'}{$ARG} //= [];
}

return <bmw384.index>;

#,,..,.,,,,..,,..,..,,,..,.,.,,,,,..,,.,,,,,,,..,,...,...,...,,,,,,..,.,.,,,,,
#752SLHA47IV4JEIWFS4DEZ3NKZ4J6FMSY5D3ZHE4GB53CYFE6AJF6WYDVNM3TOBKM4ZBEC3SKJUNY
#\\\|4DAHUBW4XI4XIEEFUSIG44X2AVJSZLCDPW4NW4IT3FHIDSQCJT7 \ / AMOS7 \ YOURUM ::
#\[7]2K3G3SOM5XXNXIGLHTE2S37UWCGKZ4OVLSXCTJTNGZCY2A4VPGBQ 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
