## [:< ##

# name  = web-browser.graph_params.install
# descr = inject graph-param sampler+renderer js into a web view
# param = <view> <js_string>

my $view      = shift;
my $js_string = shift // '';

return undef unless defined $view and length($js_string);

$view->run_javascript( $js_string, undef, undef, undef );

return TRUE;

#,,.,,,,.,.,.,.,,,..,,..,,.,.,,,,,.,,,,,.,,,.,..,,...,...,.,,,,..,...,..,,...,
#HOZLYJQ4Q5FGPHI7ASG25V6DW35CBD6EDAXRVVW5YVFMOQXJZGD5LZGURQTR77LGQDXAMQJJ5DO2G
#\\\|K2EPZCC2SHNQSYLW5UV3X46GFMOYAMU63JB3U76H5DFNX5WV6LS \ / AMOS7 \ YOURUM ::
#\[7]LWRIBCZUVGK6EJKV2YFIQJK223V7LNMSOKPBYD3IBTJE3WBXN6CQ 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
