#!/usr/bin/perl
## [:< ##

# name  = git.status
# descr = Enhanced git status with Protocol-7 colors

use v5.24;
use strict;
use English;
use warnings;

## Blacklight neon colors ##
my $reset      = "\e[0m";
my $bg         = "\e[48;2;9;5;42m";
my $blacklight = "\e[38;2;68;39;172m";
my $true_blue  = "\e[38;2;6;71;195m";
my $neon_orange = "\e[38;2;197;141;7m";
my $neon_green = "\e[38;2;71;195;6m";

exec qw| git status --short --branch |;

#,,,.,,,,,.,,,.,,,.,.,,.,,,..,,,,,.,.,,..,,,.,,,.,..,,...,...,,.,,,,.,,,.,.,.,,
#PLACEHOLDER_FOR_AMOS7_SIGNATURE_LINE_1
#\\\|PLACEHOLDER_FOR_AMOS7_SIGNATURE_LINE_2
#\[7]PLACEHOLDER_FOR_AMOS7_SIGNATURE_LINE_3
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
