#!/usr/bin/perl
## [:< ##

# name  = workspace-transfer.verify
# descr = Verify signed workspace files

use v5.24;
use strict;
use English;
use warnings;
use File::Spec;
use Cwd qw| abs_path |;
use FindBin qw| $RealBin |;

my $up_dir = File::Spec->updir;
my $p7_root = abs_path(
    File::Spec->catdir( $RealBin, ($up_dir) x 4 )
);

# Get workspace directory (auto-clones if needed)
my $ensure_workspace = File::Spec->catfile( $RealBin, 'ensure-workspace' );
my $workspace_transfer = `$ensure_workspace`;
chomp $workspace_transfer;
die "Failed to ensure workspace\n" unless $workspace_transfer && -d $workspace_transfer;

my $verify_script = File::Spec->catfile( $workspace_transfer, 'workspace-sign.pl' );

die ":\n:: workspace-transfer not found: $workspace_transfer\n\n" if !-d $workspace_transfer;
die ":\n:: workspace-sign.pl not found: $verify_script\n\n" if !-x $verify_script;

exec( $verify_script, 'verify', @ARGV );

#,,,,..,,,.,.,.,,,.,,.,,,,.,..,,.,...,,.,,,,,.,.,,,,.,.,,...,...,,.,,,.,,,,,,.,,.
#PLACEHOLDER_FOR_AMOS7_SIGNATURE_LINE_1
#\\\|PLACEHOLDER_FOR_AMOS7_SIGNATURE_LINE_2
#\[7]PLACEHOLDER_FOR_AMOS7_SIGNATURE_LINE_3
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
