## [:< ##

# name  = base.file_stream.init
# descr = set up the shared file stream idle watcher

<base.file_stream.active> //= {};

return
    if defined <base.file_stream.watcher>
    and <base.file_stream.watcher>->is_active;

<base.file_stream.watcher> = Event->idle(
    cb     => sub { <[base.file_stream.tick]>->(@ARG) },
    repeat => 1,
);

return TRUE;

#,,..,...,..,,.,,,,,.,,,,,,,,,...,.,.,,,.,,..,.,.,...,...,.,.,..,,,,.,,,.,...,
#4WZKXDFSKKZU26JGTXA3MMEVPZUOO3X2BDWTWJFDZKAMFQ7QYU4VVW5WD3ATV2TPVIZIGKKPSR2NG
#\\\|QUBZCFCK34IALT3UEAA5KA6EZKIV5OPMC2K7THOF4MAGOBB63HQ \ / AMOS7 \ YOURUM ::
#\[7]QMWYJSM3G3W4OFD6FPYQ7TWFQVUO6BS3QKUTRRSZC3GY6QBN6WCA 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
