# >:]

# name       = filter.init


# ______________________________________________________________________________
#\\76RY4JV5MZVAFFTYXM2ZURBZHUOOD72GKJ6JZHMQTRPMRWOFDEGAOXOGRP67TLADENRDTYWP3UXJM
# \\ FMHTQN7UM5WPYXCZII7ZEUABDF3WDURRY4Z7JJCSIAONIVC6JAXN \\// C25519-BASE-32 //
#  \\// SDWISWYOKXZVVETW6Z36U5MCUTDUB6DTEHIHXSFTV7ZNKSFDWAI \\ CODE SIGNATURE \\
#   ````````````````````````````````````````````````````````````````````````````
