# >:]

# name       = filter.init

# ______________________________________________________________________________
#\\IUT2MZMVG6XQHDIEIKSVDMSVLWZB62YAC32ULQSC64RKTXTPLIVZHWEH3VONWDTBB5DZTR3PZWYJI
# \\ 2BGZMUFFNEVJY5JYB7HYNR6PV53KWSZA3UYLIMBIY23ZSFSY6O2E \\// C25519-BASE-32 //
#  \\// GEAFBAMOPDCUIKFDLCK4O3RFP4TG4JPY273PHVVDYYAUJQDOWDI \\ CODE SIGNATURE \\
#   ````````````````````````````````````````````````````````````````````````````
