## [:< ##

# name  = graphics-matrix.cursor.init
# descr = initialize cursor state in graphics-matrix namespace

## initialize cursor state in data tree ##
<graphics-matrix.cursor> = {
    qw| selX   | => <graphics-matrix.cursor.initial_x> // 0,
    qw| selY   | => <graphics-matrix.cursor.initial_y> // 0,
    qw| selZ   | => <graphics-matrix.cursor.initial_z> // 0,
    qw| zoom   | => 1.0,
    qw| radius | => 1,
};

my $cursor = <graphics-matrix.cursor>;

<[base.logs]>->(
    2, 'cursor initialized at [%d,%d,%d]',
    $cursor->{'selX'}, $cursor->{'selY'}, $cursor->{'selZ'}
);

#,,,.,,,.,,,.,,,,,...,,,,,,,,,.,,,.,.,.,.,,,.,.,.,...,...,.,,,,..,..,,.,,,...,
#HI5ROLSMF42UIUNCC5X7PC722AOYF4XBWM6WAI6FAZFZ67UFDZZGIDS3JGJQCADGM24TRATLUX5HG
#\\\|BNQM7XH4MZXIPPVB5XQVPZ5GBHQLEJ7HVF5F7JEIAFEOT2ZPXER \ / AMOS7 \ YOURUM ::
#\[7]GW76YLGIQR67ZTONR7LMN2IH5EG6CNDIX6AQ52RDVZIQRASRJMAI 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
