## [:< ##

# name  = graphics-matrix.address.init
# descr = initialize address registry

## set up address registry ##
<graphics-matrix.address> = {
    qw| checksum | => {},
    qw| label    | => {},
};

## register current cursor position as origin ##
my $cursor = <graphics-matrix.cursor>;
<[graphics-matrix.address.register]>->(
    {   qw| position | => {
            qw| selX | => $cursor->{'selX'},
            qw| selY | => $cursor->{'selY'},
            qw| selZ | => $cursor->{'selZ'},
        },
        qw| label | => qw| origin |,
    }
);

<[base.logs]>->( 2, 'address registry initialized' );

#,,..,.,,,,.,,.,,,...,,..,..,,...,,,,,,..,.,.,..,,...,...,...,,.,,.,.,,.,,,,,,
#KF7YUHARLQ6MGHODSQTCVYAGQZ2YX4N2OXLUBYHYQJSVCLUMISOJPLHBQCQEBUXXYDLKUGS2WMQKM
#\\\|3AZXBFCQUYR5RRJCYGTPZU6LIZVE25EH7IX5D34I5DX4NBT2OQR \ / AMOS7 \ YOURUM ::
#\[7]UH6UTNHRJCO3LHCOMGHZIZBTIFG5ANAMOATRXTBIUFD7RFW7GKAA 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
