## [:< ##

# name  = graphics-matrix.graph.init
# descr = initialize similarity graph state

<graphics-matrix.graph> = {
    qw| edges    | => {},
    qw| clusters | => {},
    qw| count    | => 0,
};

<[base.logs]>->( 2, 'graph initialized' );

#,,..,.,.,,,.,..,,.,,,..,,,,.,,,,,.,,,.,.,...,..,,...,...,..,,..,,.,,,,..,.,,,
#B62HLOEJ6FP423LCQ2PX5APHGZWMTHRU36JKHB53SPWXBB5WPG4LCVS5N5FYZNNAGWP27E64ARSKU
#\\\|S7B7G4C6Q2VCTG2HPIKDUUVJ4YYZAV4EZE62REWMNSBCSL5ARZ2 \ / AMOS7 \ YOURUM ::
#\[7]NJELT5FUWNXR7R7XV3FC5IWKJTFU5P6VBOG6PORHEU3I4XGTGKCI 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
