## [:< ##

# name  = graphics-matrix.cell.init
# descr = initialize lattice cell storage

## set up cell storage ##
<graphics-matrix.cell> = {
    qw| cells | => {},
    qw| count | => 0,
};

<[base.logs]>->( 2, 'cell storage initialized' );

#,,..,,,.,,..,,,.,,.,,,.,,...,.,,,,,,,,..,,.,,..,,...,...,..,,,,.,.,,,.,.,,..,
#EUBBLLGVNHZSPLM3FOQMC5KST2GRJHYW6KUML6WQ3EVWFINZCWO7WMLRBGCIRZUKBTUCQ4GF6FDVC
#\\\|PTF75NFKKKBOWSETXWJ6WRMPKB55H4ZWTUDHW7RB3IZLETAHTS7 \ / AMOS7 \ YOURUM ::
#\[7]7J2FOS5IOIW6BVHADFMRQMM6TG5U2CHUVE62FOTDLRBBEF4HPADY 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
