## [:< ##

# name  = jobsite.assert.init
# descr = create assertion tree template for a job entry

my $job_id = <[base.vax-int.decode]>->( shift // '' );
return if not length $job_id;

my $assertions = {
    'suggest' => {
        'apply'   => 'undecided',
        'delete'  => 'undecided',
        'archive' => 'undecided',
    },
    'dimensions' => {
        'location' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'work-profile' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'company-culture' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'compensation' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'remote-flexibility' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'career-growth' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'tech-stack' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
        'team-structure' => {
            'score'  => 'unasserted',
            'reason' => '',
        },
    }
};

<jobsite.tasks>->{$job_id}{'assertions'} = $assertions;

return $assertions;

#,,..,.,,,..,,,..,,.,,.,,,..,,,.,,.,,,,.,,,..,..,,...,...,.,,,..,,...,..,,.,.,
#DFP5TGHAK5T6QDFFTOIXZGATET2COFKIDOGDYH5ZXSPMLWXRGFODOEFLDAQRGA4SCG3WNMLZOFVM6
#\\\|CUJ7DK5PHYTTP3T2IKOV432CZNUJVSRKEEHHOAXJNSJW57FA2E7 \ / AMOS7 \ YOURUM ::
#\[7]XGGQGRL43DBQEO7MYH7MGHEHZC4WYCH2XSGCAUFXN3M3MQPB4OCA 7  DATA SIGNATURE ::
#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
